name: Jekyll site CI

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}/docs:/srv/jekyll -v ${{ github.workspace }}/docs/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "set -ex && apk add --update && chmod 777 /srv/jekyll && bundle config set path 'vendor/cache' && bundle install --path vendor/cache && jekyll build --future"
